name: entropy-check

on:
  push:
    branches: [main-GitHub-Action] 
  pull_request:
    branches: [main-GitHub-Action]

jobs:
  entropy-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python env
        uses: ./.github/actions/install-python-env
      - name: Run entropy report
        run: |
          poetry run almanack process_repo_entropy . > report.txt
          
          # Extract the report
          cat report.txt
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('report.txt', 'utf8');
            const prNumber = process.env.GITHUB_REF.replace('refs/pull/', '').replace('/merge', '');
            
            const comment = `### Entropy Report\n\n${report}`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: comment
            });
