---
name: entropy-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python env
        uses: ./.github/actions/install-python-env

      - name: Process repository entropy
        run: poetry run almanack process_repo_entropy . > entropy_report.txt

      - name: Format Entropy Report
        id: format_report
        run: |
          CONTENT=$(sed 's/"/\\"/g' entropy_report.txt | awk '{print}' ORS='\n')
          {
            echo "REPORT_CONTENT<<EOF";
            echo "$CONTENT";
            echo "EOF";
          } >> "$GITHUB_ENV"

      - name: PR comment
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            ${{ env.REPORT_CONTENT }}
          comment_tag: execution
          mode: recreate
        # env:
        #   GITHUB_TOKEN: ${{ secrets.ENTROPY_PR_COMMENT }}

