---
name: entropy-check

on:
  pull_request_target:
    branches:
      - main

jobs:
  entropy-check:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install python env
        uses: ./.github/actions/install-python-env

      - name: Process repository entropy
        run: poetry run almanack process_repo_entropy . > entropy_report.txt

      - name: Format Entropy Report
        id: format_report
        run: |
          {
            echo "REPORT_CONTENT<<EOF";
            echo "\`\`\`";
            cat entropy_report.txt;
            echo "\`\`\`";
            echo "EOF";
          } >> "$GITHUB_ENV"

      - name: PR comment
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          message: |
            ${{ env.REPORT_CONTENT }}
          comment_tag: execution
          mode: recreate
