---
name: entropy-check

on:
  push:
    branches:
      - main
      - GitHub-Action
  pull_request:
    branches:
      - main
      - GitHub-Action
jobs:
  entropy-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install python env
        uses: ./.github/actions/install-python-env

      - name: Display working directory
        run: pwd
      
      - name: List directory contents
        run: ls -la

      - name: Show git log
        run: git log --oneline

      - name: Run entropy report
        run: |
          poetry run almanack process_repo_entropy .