# used for running pytest tests
name: test-pr-comment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # tests the build of book content
  test-pr-comment:
    runs-on: "ubuntu-22.04"
    permissions: 
      pull-requests: write
    steps:
      - name: PR comment with reactions
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.ENTROPY_PR_COMMENT }}
