name: Test GITHUB_ENV

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set and Display PR Branch Environment Variables
        env:
          PR_BRANCH: ${{ github.head_ref }}
          MAIN_BRANCH: ${{ github.base_ref }}
        run: |
          echo "PR_BRANCH=${PR_BRANCH}" >> $GITHUB_ENV
          echo "MAIN_BRANCH=${MAIN_BRANCH}" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Check Environment Variables
        run: |
          echo "PR_BRANCH is: $PR_BRANCH"
          echo "MAIN_BRANCH is: $MAIN_BRANCH"
